routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::resource('questions', QuestionsController::class)->middleware(['auth'])->except('show');
Route::get('questions/{slug}',[QuestionsController::class, 'show'])->name('questions.show');
Route::resource('questions.answers', AnswersController::class)->except(['index','show','create']);
Route::put('answers/{answer}/best-answer',[AnswersController::class, 'bestAnswer'])->name('answers.bestAnswer');
Route::post('questions/{question}/favorite',[FavoritesController::class, 'store'])->name('questions.favorite');
Route::delete('questions/{question}/unfavorite',[FavoritesController::class, 'destroy'])->name('questions.unfavorite');
Route::post('question/{question}/vote/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.votes');
Route::post('answers/{answer}/vote/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.votes');
Route::get('users/notifications', [UsersController::class, 'notifications'])->name('users.notification');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Answer.php
<?php

namespace App\Models;

use App\Helpers\Votable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Answer extends Model
{

    use HasFactory;
    use Votable;
    protected $guarded = ['id'];
    
    public static function boot()
    {
        parent::boot();
        static::created(function(Answer $answer){
            $answer->question->increment('answers_count');
        });
        static::deleted(function(Answer $answer){
            $answer->question->decrement('answers_count');
        });
    }

    public function getBestAnswerStyleAttribute()
    {
        if($this->id === $this->question->best_answer_id)
        {
            return "text-success";
        }
        return "text-dark";
    }

    public function getIsBestAnswerAttribute()
    {

        return $this->id === $this->question->best_answer_id;
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    //Relationship Methods
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favorites()
    {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }
    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }
    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }

    public function hasQuestionUpVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => 1, 'vote_id' => $question->id, 'vote_type' => Question::class])->exists();
    }
    public function hasQuestionDownVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => -1, 'vote_id' => $question->id, 'vote_type' => Question::class])->exists();
    }
    public function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }


    public function hasAnswerUpVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => 1, 'vote_id' => $answer->id, 'vote_type' => Answer::class])->exists();
    }
    public function hasAnswerDownVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => -1, 'vote_id' => $answer->id, 'vote_type' => Answer::class])->exists();
    }
    public function hasVoteForAnswer(Answer $answer)
    {
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }

    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Answers\CreateAnswerRequest;
use App\Http\Requests\Answers\UpdateAnswerRequest;
use App\Http\Requests\Questions\UpdateQuestionRequest;
use App\Models\Answer;
use App\Models\Question;
use App\Notifications\NewAnswerAdded;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    public function store(Question $question, CreateAnswerRequest $request)
    {
        $question->answers()->create(['body' => $request->body, 'user_id' => auth()->id()]);

        $question->owner->notify(new NewAnswerAdded($question));
        session()->flash('success', 'Your answered is Added!');
        return redirect($question->url);
    }

    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);
        return  view('answers.edit', compact(['question','answer']));
    }

    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        $this->authorize('update',$answer);
        $answer->update(['body'=>$request->body]);
        session()->flash('success', 'Your answered is Edited!');
        return redirect($question->url);
    }

    public function destroy(Question $question, Answer $answer)
    {
        $this->authorize('delete',$answer);
        $answer->delete();
        session()->flash('success', 'Answered is Deleted!');
        return redirect($question->url);
    }

    public function bestAnswer(Answer $answer)
    {
        $this->authorize('markAsBest',$answer);
        $answer->question->markBestAnswer($answer);
        return redirect()->back();
    }
}

resources/views/answers/_create.blade.php
<div class="row mt-4 justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h2>Your Answer</h2>
            </div>
            <div class="card-body">
                <form action="{{ route('questions.answers.store', $question->id) }}" method="POST">
                    @csrf
                    <div class="form-group">

                        <input type="hidden" id="body" name="body" value="{{ old('body') }}">
                        <trix-editor input="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}"></trix-editor>
                        @error('body')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_index.blade.php
<div class="row mt-3">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="mt-0">{{ \Illuminate\Support\Str::plural('Answer', $question->answers_count) }}</h3>
            </div>
            <div class="card-body">
                @foreach ($question->answers as $answer)
                    {!! $answer->body !!}
                    <div class="d-flex justify-content-between">
                        <div class="d-flex">
                            <div>
                                @auth
                                    <form action="{{ route('answers.votes', [$answer->id, 1]) }}" method="POST">
                                        @csrf
                                        <button title="Up-vote" type="submit" class="btn {{ auth()->user()->hasAnswerUpVote($answer) ? 'text-success' : 'text-black-50' }}">
                                            <i class="fa fa-caret-up fa-3x"></i>
                                        </button>
                                    </form>
                                @else
                                    <a href="{{ route('login') }}" class="vote-up d-block text-center text-black-50" title="Up-Vote">
                                        <i class="fa fa-caret-up fa-3x"></i>
                                    </a>
                                @endauth
                                <a href="" class="vote-up d-block text-center text-black-50" title="Up-Vote">

                                </a>
                                <h4 class="m-0 text-muted text-center vote-count">{{ $answer->votes_count }}</h4>
                                @auth
                                    <form action="{{ route('answers.votes', [$answer->id, -1]) }}" method="POST">
                                        @csrf
                                        <button title="Down-vote" type="submit" class="btn {{ auth()->user()->hasAnswerDownVote($answer) ? 'text-danger' : 'text-black-50' }}">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </button>
                                    </form>
                                @else
                                    <a href="{{ route('login') }}" class="vote-up d-block text-center text-black-50" title="Down-Vote">
                                        <i class="fa fa-caret-down fa-3x"></i>
                                    </a>
                                @endauth
                            </div>

                            <div class="ml-5 mt-3">
                                @can('markAsBest', $answer)
                                    <form action="{{ route('answers.bestAnswer', $answer->id) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button title="Mark as Correct" type="submit" class="btn {{ $answer->best_answer_style }}">
                                            <i class="fa fa-check fa-2x"></i>
                                        </button>
                                    </form>

                                @else
                                    @if ($answer->is_best_answer)
                                        <i class="fa fa-check fa-2x text-success d-block mb-2"></i>
                                    @endif
                                @endcan


                                <h4 class="m-0 text-muted text-center views-count">145</h4>
                            </div>
                        </div>
                        <div class="justify-content-between text-center">
                            @can('update',$answer)
                                <a href="{{ route('questions.answers.edit', [$question->id, $answer->id]) }}" class="btn btn-warning ml-5">Edit</a>
                            @endcan
                            @can('delete',$answer)
                                <form class="d-inline" action="{{ route('questions.answers.destroy' ,[$question->id, $answer->id]) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger ml-3"
                                            type="submit"
                                            onclick="return confirm('Are you sure, You want to delete this answer?')"
                                    >Delete</button>
                                </form>
                            @endcan
                        </div>
                        <div class="d-flex flex-column">
                            <div class="text-muted mb-2 text-right mt-2">
                                <p>Answered {{ $answer->created_date }}</p>
                            </div>
                            <div class="d-flex mb-2">
                                <div>
                                    <img src="{{ $answer->author->avatar }}" alt="">
                                </div>
                                <div class="mt-2 ml-2">
                                    <p>{{ $answer->author->name }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/answers/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row mt-4 justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Edit your Answer</h2>
                </div>
                <div class="card-body">
                    <form action="{{ route('questions.answers.update', [$question->id,$answer->id]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">

                            <input type="hidden" id="body" name="body" value="{{ old('body',$answer->body) }}">
                            <trix-editor input="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}"></trix-editor>
                            @error('body')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success" type="submit">Edit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js" integrity="sha512-/1nVu72YEESEbcmhE/EvjH/RxTg62EKvYWLG3NdeZibTCuEtW5M4z3aypcvsoZw03FAopi94y04GhuqRU9p+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@endsection
@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" integrity="sha512-CWdvnJD7uGtuypLLe5rLU3eUAkbzBR3Bm1SFPEaRfvXXI2v2H5Y0057EMTzNuGGRIznt8+128QIDQ8RqmHbAdg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection